### ISSUE TITLE
适配文档分屏（获取挂件所在文档的元素）

### ISSUE THREAD

**Issue by TCOTC** [hqweay/widget-inline-extractor#5]
两篇文档左右分屏显示，挂件会显示获取左边文档的元素

![image](https://github.com/hqweay/widget-inline-extractor/assets/78434827/da142bf3-027b-4a68-95c7-7792689317c0)

**Comment by hqweay** [comment]
感谢，这是 bug 了。应该取文档的内容，现在取成活动窗口的内容了。我改下。

**Comment by hqweay** [comment]
0.0.3 应该修复了
