### ISSUE TITLE
版本号修改之后才能 Publish release，release 和 commit 要对应

### ISSUE THREAD

**Issue by TCOTC** [hqweay/widget-inline-extractor#8]
现在挂件一直提示更新：

![image](https://github.com/hqweay/widget-inline-extractor/assets/78434827/18cf0bc1-0307-4fc5-a008-47c359ef8546)

关联：https://github.com/siyuan-note/siyuan/issues/11007#issuecomment-2052816656

**Comment by hqweay** [comment]
感谢。修改了下0.0.2的tag和包，不知道集市的逻辑如何，能不能把状态同步过去。不行的话等下次打包叭。

**Comment by TCOTC** [comment]
要等下次打包了

**Comment by hqweay** [comment]
打了个 0.0.3 的包应该可以了
